### PR TITLE
Add support to v0.119.0

### PR DESCRIPTION
**Pull request by eval-exec**
Add support to v0.119.0

### CODE REVIEW

**Comment by eval-exec** [comment]
https://github.com/nervosnetwork/ckb-sdk-go/actions/runs/11550940849/job/32146933687?pr=226


```go
var c, _ = Dial("https://mercury-testnet.ckbapp.dev/0.4")
```
It seems that mercury api endpoint is down?
@jiangxianliang007

**Comment by jiangxianliang007** [comment]
> https://github.com/nervosnetwork/ckb-sdk-go/actions/runs/11550940849/job/32146933687?pr=226
> 
> ```go
> var c, _ = Dial("https://mercury-testnet.ckbapp.dev/0.4")
> ```
> 
> It seems that mercury api endpoint is down? @jiangxianliang007

After hardfork mercury is no longer compatible and the service is offline. CI should not rely on third-party api's.

**Comment by eval-exec** [comment]
Invite @quake to review, and create a new release for ckb-sdk-go.

**Review by zhangsoledad — APPROVED** [review]

**Comment by eval-exec** [comment]
@zhangsoledad Please create a git tag v2.3.0 on latest v2 branch.

**Pull request merged**
